// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/crm-naming-variants/ClearerHierarchy.tsx": () => import("../components/mockups/crm-naming-variants/ClearerHierarchy.tsx"),
  "./components/mockups/crm-naming-variants/TighterPrecision.tsx": () => import("../components/mockups/crm-naming-variants/TighterPrecision.tsx")
};
